In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv("survey_results_public.csv")
df2 = pd.read_csv("survey_results_schema.csv")

In [4]:
df1

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

loc and iloc

In [ ]:
# Loc and iloc
# Loc - uses mix of indices and names
df1.loc[[0, 1], ["Hobbyist"]] # Acces one column

  Hobbyist
0      Yes
1       No

In [7]:
df1.loc[[0, 1], ["Hobbyist", "OpenSourcer"]] # Access multiple column

  Hobbyist              OpenSourcer
0      Yes                    Never
1       No  Less than once per year

In [8]:
df1.loc[[0, 1, 2, 3], ["Hobbyist", "OpenSourcer", "Country"]] # Access multiple column

  Hobbyist              OpenSourcer                 Country
0      Yes                    Never          United Kingdom
1       No  Less than once per year  Bosnia and Herzegovina
2      Yes                    Never                Thailand
3       No                    Never           United States

In [11]:
# Exception:  ending element pani include garxa loc lae
df1.loc[0:10, "Hobbyist":"Country"] # Access multiple column

,Hobbyist,OpenSourcer,OpenSource,Employment,Country
0,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom
1,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina
2,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand
3,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States
4,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine
5,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Canada
6,No,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Ukraine
7,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India
8,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand
9,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India
10,Yes,Once a month or more often,The quality of OSS and closed source software ...,NaN,Antigua and Barbuda

In [13]:
# iloc : uses only integer indices
# Exception:  ending element pani include garxa loc lae
df1.iloc[[0, 1, 2], [0, 1, 2, 3, 4]]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...

In [14]:
df1.iloc[0:3, 0:5]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...

In [ ]:
# Temporarely change indices
df1.set_index("Respondent")

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [24]:
# Permanently change indices
df1.set_index("MainBranch", inplace=True)

KeyError: "None of ['MainBranch'] are in the columns"

In [25]:
df = pd.DataFrame({"F_name": ["Samriddha", "Samip"],
                   "L_name": ["Pathak", "Karki"],
                   "e_mail": ["samriddha@gmail.com", "samip@gmail.com"]})

In [26]:
df.set_index("e_mail", inplace=True)

In [27]:
df

                        F_name  L_name
e_mail
samriddha@gmail.com  Samriddha  Pathak
samip@gmail.com          Samip   Karki

In [28]:
df.loc["samriddha@gmail.com", ["F_name", "L_name"]]

F_name    Samriddha
L_name       Pathak
Name: samriddha@gmail.com, dtype: object

In [29]:
df2

          Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

In [ ]:
# Remove certain columns; axis = 0: Row> Row ko lagi indices pass garnae, axis=1: Column > column ko lagi name pass garnae
df2.drop(1, axis=0, inplace=True)  # Drop row with index 2

In [36]:
df2

          Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
5     Employment  Which of the following best describes your cur...
6        Country          In which country do you currently reside?
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[83 rows x 2 columns]

In [37]:
df2.drop("QuestionText", axis=1, inplace=True)  # Drop column with name "QuestionText"

In [38]:
df2

          Column
0     Respondent
3    OpenSourcer
4     OpenSource
5     Employment
6        Country
..           ...
80     Sexuality
81     Ethnicity
82    Dependents
83  SurveyLength
84    SurveyEase

[83 rows x 1 columns]

In [39]:
df

                        F_name  L_name
e_mail
samriddha@gmail.com  Samriddha  Pathak
samip@gmail.com          Samip   Karki

In [40]:
df.drop("samriddha@gmail.com", axis=0, inplace=True)  # Drop row with index "

In [41]:
df

                F_name L_name
e_mail
samip@gmail.com  Samip  Karki